/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: markus.williams (https://sketchfab.com/markus.williams)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1ign-dna-binding-domain-dbd-of-yeast-rap1-0e8f9eaedac24bb0bf98bc748094aaf2
Title: 1IGN - DNA Binding Domain (DBD) of Yeast RAP1
*/

"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Dna(props) {
  const { nodes, materials } = useGLTF("/models/scene-transformed-dna.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["geom22403-material"].geometry}
        material={materials["geom0-material"]}
        position={[10.304, -31.268, 20.4]}
        rotation={[-1.287, -0.532, 0.209]}
      />
    </group>
  );
}

useGLTF.preload("/models/scene-transformed-dna.glb");
