/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: gvsuchem (https://sketchfab.com/gvsu-chem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beta-hairpin-from-protein-g-99cceab6d2c04c279130c15fc293db4f
Title: Beta Hairpin from Protein G
*/

"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Protein(props) {
  const { nodes, materials } = useGLTF("/models/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <lineSegments
        geometry={nodes.Object_3.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/scene-transformed.glb");
